server:
  port: 7000

spring:
  application:
    name: phj-crowd-pay
  redis:
    host: 192.168.220.129
    password: root
  session:
    store-type: redis

ribbon:
  # 修改ribbon默认的超时时间
  ReadTimeout: 30000
  ConnectTimeout: 30000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/                # eureka 注册中心的地址

ali:
  pay:
    alipay-public-key: xxx
    app-id: xxx
    charset: utf-8
    gateway-url: xxx
    merchant-private-key: xxx
    notify-url: http://xxx
    return-url: http://localhost/pay/return
    sign-type: xxx
